version: '3.7'
services:
  mf-database:
    container_name: mf-database
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mf_backend
    ports:
      - 3306:3306
    networks:
      - mf

networks:
  mf:
    name: mf